### PR TITLE
Display bugs with needinfo with a specific style

### PR DESCRIPTION
**Pull request by nchevobbe**
Fixes https://github.com/nchevobbe/bugzilla-timeline/issues/24 

screenshot at sept 01 18-37-15

@nt1m , @hwine , does it sound good to you ?

### CODE REVIEW

**Comment by hwine** [comment]
@nchevobbe - one question - how does it look if the bug was assigned to me today & has a needinfo? i.e. line is shorter than marker. 

Certainly meets my needs! Thanks!

**Comment by nchevobbe** [comment]
@hwine there migh be a minimal width so the line isn't too short

**Comment by nt1m** [comment]
What's the difference between the first square marker and the one on the third line?

**Comment by hwine** [comment]
@nt1m:
- top line is open issue with an open "need info"
- 2nd line is open issue
- 3rd line is issue closed, other than RESOLVED/FIXED (e.g. WONTFIX)
- bottom line is issue closed RESOLVED/FIXED

**Comment by nt1m** [comment]
@hwine ok, thanks.
@nchevobbe Looks good to me !

**Pull request merged**
